In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [12]:
import time

a=np.random.rand(10000000)
b=np.random.rand(10000000)

tic = time.time()
c=np.dot(a,b)
toc = time.time()

print("Vectorized Dot Product: " + str(1000*(toc-tic)) + "ms")

Vectorized Dot Product: 13.711929321289062ms


In [13]:
c = 0
tic = time.time()

for i in range(10000000):
    c+=a[i]*b[i]

toc = time.time()

print("FOR LOOP: "+ str(1000*(toc-tic)) + "ms")

FOR LOOP: 3182.191848754883ms


In [14]:
import math

v = np.random.rand(10000000)

tic = time.time()
u = np.zeros((10000000,1))
for i in range(10000000):
    u[i] = math.exp(v[i])
toc = time.time()

print("NON VECTORIZED TIME: " + str(1000*(toc-tic)) + "ms")

NON VECTORIZED TIME: 4903.825998306274ms


In [15]:
tic = time.time()
u = np.exp(v)
toc = time.time()
print("Vectorized time: " + str(1000*(toc-tic)) + "ms")

Vectorized time: 103.31892967224121ms


In [18]:
# using vectorization in logistic regression
# z(i) = Wt*x(i) + b

nx = 10  # number of dependency variables
m = 100 # number of training datasets
b = np.random.rand()

w = np.random.rand(nx,1)
X = np.random.rand(nx,m)

# Z = Wt*X + [b b b b....b]

tic = time.time()
Z = np.dot(w.T,X) + b
toc = time.time()

print(Z)
print("TIME TAKEN: " + str(1000*(toc-tic)) + "ms")

[[4.04852782 4.15334814 4.25379977 2.38448677 3.74593508 3.42184498
  4.17757627 3.1276271  4.54374983 3.82151794 3.81661484 2.95194298
  5.50788055 3.25414629 3.82644181 3.76065377 4.0767989  3.29853484
  3.20539142 4.39651818 3.89382739 3.99711889 2.78744087 3.99632281
  4.10509693 4.32063059 4.01543014 5.2502588  4.48315195 4.34028822
  3.42110771 3.06282048 3.87556057 3.32573478 3.5284194  3.00991242
  3.88898663 4.01078703 3.48888992 3.20021594 3.55059244 4.84419336
  3.63554336 4.00250208 3.06084579 4.46934451 2.66322779 3.42055194
  3.22642706 2.80791752 3.28979142 3.9717406  3.29649383 3.58613381
  3.66110852 2.46573165 4.63408163 4.21376772 3.63346712 3.29339689
  4.23865526 3.81024095 3.39773001 3.83191616 4.37301205 2.80679171
  3.82273474 3.98575058 3.80476864 3.47163491 4.12334756 4.35507868
  3.95998136 3.03720251 4.82707246 4.07257896 4.48553366 3.49719946
  4.0321976  2.99661694 3.46120776 3.11467424 3.10704053 4.17628773
  2.96274498 4.40033029 2.92782623 3.15781346 2.

In [19]:
# Broadcasting Example

A = np.array([[56.0,0.0,4.4,68.0],
              [1.2,104.0,52.0,8.0],
              [1.8,135.0,99.0,0.9]])
print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [20]:
cal = A.sum(axis = 0)
print(cal)

[ 59.  239.  155.4  76.9]


In [22]:
percentage = 100*A/cal
print(percentage)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]
